name: XLEVEL
favicon: null
layout_spectrum: 0.07475437759421766
typography_spectrum: 0.03698345413431525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6110524947289377
  lightness: 0.5114791132509708
  saturation: 0.3459094329737127
  rhythmicContrast: 0.8005249700509012
purpose: []
